### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by phuvio** [kodtld/Markov-s-Letters#1]
*Loaded the project 18.2. at 16.10 o'clock.*

Based on the code, the project seems to have progressed well. Unfortunately, I was not able to test the program itself. The server started, but when I tried to go to the page http://localhost:5000/, the page reported an error: LookupError. The program was tested on the university's Linux laptop. I attached the error message after the comments.

**Comments**

- Program did not start. Error seems to be related to Natural Language Toolkit. Program cannot find it even though it is added to Poetry's installations.
- Classes Trie and TrieNode are in the same file, but you could move them to their own files for clarity.
- Comments on classes and methods could be developed. By adding which arguments the methods accept and on the other hand which values they return, you clarify the readability of the code. There is a good plugin for autocomposing comments: [Python Docstring Generator](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring).
- Regarding Git commits/messages, you could use recommended practices for them, e.g. https://chris.beams.io/posts/git-commit/

Otherwise, the code was clear and it was structurally well put together. Also the test coverage was good and also performance of the program was tested extensively. Well done.

**Error message**

LookupError: 
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  \>>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m

  Searched in:
      - '/home/pehuvio/nltk_data'
      - '/home/pehuvio/.cache/pypoetry/virtualenvs/flask-server-AOs_4Kr6-py3.10/nltk_data'
      - '/home/pehuvio/.cache/pypoetry/virtualenvs/flask-server-AOs_4Kr6-py3.10/share/nltk_data'
      - '/home/pehuvio/.cache/pypoetry/virtualenvs/flask-server-AOs_4Kr6-py3.10/lib/nltk_data'
      - '/usr/share/nltk_data'
      - '/usr/local/share/nltk_data'
      - '/usr/lib/nltk_data'
      - '/usr/local/lib/nltk_data'
      - ''
**********************************************************************

**Comment by kodtld** [comment]
Thanks for the feedback!
