### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by TeemuBergman** [kodtld/Markov-s-Letters#2]
**Projekti ladattu 26.2. klo 14:55.**

- Projektissa on kaksi Poetryn käyttämää `pyproject.toml` -tiedostoa (ensimmäinen projektin juuressa ja toinen 'flask-server' -kansiossa). Vahva suositus vain yhdelle tiedostolle projektin juuressa, sillä nyt piti ensin testata, että kummalla asennuksella projektin saa toimimaan. Liittyykö tämä ratkaisu testausdokumentissa mainittuun yksikkötestaukseen vai onko tiedosto epähuomiossa siirtynyt väärään kansioon?
- Käyttöliittymä on selkeä ja siten yksinkertainen käyttää. Ehdottaisin, että laittaisit `Select a state for Markov (1-5)` -valintaan kuitenkin jonkin pienen selityksen siitä, miten se vaikuttaa algoritmin toimintaan ja saatuun lopputulokseen?
- Tiedosto `server.py` sisältää funktion `generate_senteces`, jonka toiminta on projektin pää-algoritmin toiminnan kannalta sen verran keskeinen, että refaktoroisin sen samaan `services` kansioon sen muiden osien kanssa.
- Siirtäisin `performance_markov.py` ja `performance_trie.py` -tiedostot omaan kansioonsa, vaikkapa sitten `performance` nimiseen sellaiseen. Tämä auttaisi pitämään projektin rakenteen hieman järjestelmällisempänä.
- `.gitignore` -tiedostoon kannataa lisätä `__pycache__` -kansio, sillä se on nyt vain ylimääräistä sisältöä.
- Projektin käynnistämiseen liittyen Invoke-kirjasto on erittäin näppärä, jota käyttämällä projektin voi käynnistää yksinkertaisella komennolla, esimerkiksi: `invoke start`, tai suorittaa testikattavuuden raportointiin tarvittavat komennot yhdellä komennolla. Vaikka et päätyisi edellä mainittua kirjastoa käyttämään, ohjeistukseen kannataa kuitenkin lisätä miten projektin saa käyntiin.
- Yksikkötestauksen saa toimimaan myös projektin juuresta viittaamalla `flask-server` -kansioon: `coverage run -m pytest flask-server/tests`.
- Yleisesti projektin koodi on mielestäni selkeää ja hyvin kommentoitua eikä itse algoritmeissä vaikuttaisi olevan mitään sen erityisempää kommentoitavaa. Hyvältä siis vaikuttaa!

**Comment by kodtld** [comment]
Kiitos palautteesta! Rakenteelliset ja repositorioon liittyvät korjaukset olivat jo työlistalla, mutta lisään selityksen Select statelle käyttöliittymään.
